apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: kube-system
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: michelaap/node-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: kube-system
  labels:
    service: node-app
spec:
  type: NodePort
  ports:
    - port: 3000
      name: web
  selector:
    app: node-app
